security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        samurai_db_provider:
            entity: 
                class: App\Entity\User
                property: username
           
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern: ^/
            # gaurd:
            #     authenticators:
            #         - app.security.login_form_authenticator

        
    access_control:
        - { path: ^/admin, roles: ROLE_USER }
    
    encoders:
        App\Entity\User:
            algorithm: bcrypt
       

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
