security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        samurai_db_provider:
            entity:
               class: App\Entity\User
               property:  username
    
    role_hierarchy:
        ROLE_ADMIN:   ROLE_USER
        ROLE_SUPER_ADMIN:  ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login
                use_forward: false
                provider: samurai_db_provider
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            stateless: false
            logout:
                path:  /logout
                target: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/nominate, role: ROLE_USER }


    encoders:
        App\Entity\User:
            algorithm: bcrypt


            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
