index:
   path: /
   controller: App\Controller\DefaultController::index

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

app_api:
   resource: ../src/Controller/Api
   type:     annotation

logout:
    path: /logout
